version: '3.4'

services:
  takeshi.api:
    image: takeshiapi
    build:
      context: .
      dockerfile: Api/Dockerfile
    ports:
     - "7101:80"
    environment:
      - Takeshi.RabbitMq.Host={placeholder}
      - Takeshi.RabbitMq.User={placeholder}
      - Takeshi.RabbitMq.Password={placeholder}
  takeshi.application:
    image: takeshiapplication
    build:
      context: .
      dockerfile: Service.Host/Dockerfile
    environment:
      - Takeshi.RabbitMq.Host={placeholder}
      - Takeshi.RabbitMq.User={placeholder}
      - Takeshi.RabbitMq.Password={placeholder}
